openapi: 3.0.3
info:
  title: OpenAPI schema for template test-upgrade
components:
  schemas:
    variables:
      type: object
      properties:
        test_str:
          title: Test Str
          type: string
          default: variable-test
          x-walrus-ui:
            group: Basic
            order: 1
        test_num_without_type:
          title: Test Num Without Type
          type: number
          default: 123
          x-walrus-ui:
            group: Basic
            order: 2
        test_bool:
          title: Test Bool
          type: boolean
          default: false
          x-walrus-ui:
            group: Basic
            order: 3
        test_list_number:
          title: Test List Number
          type: array
          default:
          - 80
          - 443
          items:
            type: number
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        test_map_without_type:
          title: Test Map Without Type
          type: object
          default:
            age2: "30"
            email2: john@example.com
            name2: John
          required:
          - age2
          - email2
          - name2
          properties:
            age2:
              title: Age2
              type: string
            email2:
              title: Email2
              type: string
            name2:
              title: Name2
              type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        map_any:
          title: Map Any
          type: object
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
            widget: YamlEditor
        list_map_string:
          title: List Map String
          type: array
          description: List of maps containing node pools
          default:
          - name: default-node-pool
          items:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        map_string:
          title: Map String
          type: object
          default:
            Department: Engineering
            Environment: Production
            Name: MyInstance
            Owner: John Doe
          additionalProperties:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
        test_object_with_default_optional:
          title: Test Object With Default Optional
          type: object
          default:
            age: 23
            email:
              address: bob
              domain: example.com
            name: Bob
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
